# Generated by Django 4.0.4 on 2022-07-05 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="nutriscore",
            field=models.URLField(null=True),
        ),
    ]
