# Generated by Django 4.0.4 on 2022-07-05 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_nutriscore"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="nutriscore",
            field=models.CharField(max_length=1),
        ),
    ]
