# Generated by Django 4.0.4 on 2022-09-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_nutriscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='product',
            name='stores',
            field=models.CharField(max_length=512),
        ),
    ]
